import { app } from 'electron';
import { drizzle } from 'drizzle-orm/node-sqlite';
import { migrate } from 'drizzle-orm/node-sqlite/migrator';
import * as fs from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import * as path from 'node:path';
import { getEnvironment } from '../environment/environment.module';
import { MIGRATIONS_DIRNAME } from './database.tokens';
import * as schema from './schema/index';

export type DB = ReturnType<typeof createDb>;

let _db: DB | undefined;

/**
 * Resolves the database file from the active environment (environments/*.yml):
 * `directory: userData` maps to Electron's user-data dir; anything else is a
 * directory path. DASHBOARD_DB overrides everything (e.g. test databases) —
 * drizzle.config.ts mirrors this same resolution for the CLI.
 */
function resolveDbFile(): string {
  if (process.env['DASHBOARD_DB']) return process.env['DASHBOARD_DB'];
  const { database } = getEnvironment();
  const dir =
    database.directory === 'userData' ? app.getPath('userData') : path.resolve(database.directory);
  fs.mkdirSync(dir, { recursive: true });
  return path.join(dir, database.fileName);
}

function createDb() {
  const sqlite = new DatabaseSync(resolveDbFile());
  // Sensible defaults for a desktop app.
  sqlite.exec('PRAGMA journal_mode = WAL;');
  sqlite.exec('PRAGMA foreign_keys = ON;');
  // Pass `relations` to enable the v2 relational query API (db.query.*).
  return drizzle({ client: sqlite, schema, relations: schema.relations });
}

/** Initializes the connection and applies pending migrations. Call once on app ready. */
export function initDb(): DB {
  if (_db) return _db;
  _db = createDb();
  // Migrations are generated by drizzle-kit into ./drizzle (bundled with the app).
  migrate(_db, { migrationsFolder: path.join(app.getAppPath(), MIGRATIONS_DIRNAME) });
  return _db;
}

/** Returns the initialized db. Throws if initDb() hasn't run yet. */
export function getDb(): DB {
  if (!_db) throw new Error('Database not initialized — call initDb() first.');
  return _db;
}
