import { app } from 'electron';
import { drizzle } from 'drizzle-orm/node-sqlite';
import { migrate } from 'drizzle-orm/node-sqlite/migrator';
import { DatabaseSync } from 'node:sqlite';
import * as path from 'node:path';
import { DB_FILENAME, MIGRATIONS_DIRNAME } from './database.tokens.js';
import * as schema from './schema/index.js';

export type DB = ReturnType<typeof createDb>;

let _db: DB | undefined;

function createDb() {
  // Store the database alongside the app's user data, not in the bundle.
  const file = path.join(app.getPath('userData'), DB_FILENAME);
  const sqlite = new DatabaseSync(file);
  // Sensible defaults for a desktop app.
  sqlite.exec('PRAGMA journal_mode = WAL;');
  sqlite.exec('PRAGMA foreign_keys = ON;');
  // Pass `relations` to enable the v2 relational query API (db.query.*).
  return drizzle({ client: sqlite, schema, relations: schema.relations });
}

/** Initializes the connection and applies pending migrations. Call once on app ready. */
export function initDb(): DB {
  if (_db) return _db;
  _db = createDb();
  // Migrations are generated by drizzle-kit into ./drizzle (bundled with the app).
  migrate(_db, { migrationsFolder: path.join(app.getAppPath(), MIGRATIONS_DIRNAME) });
  return _db;
}

/** Returns the initialized db. Throws if initDb() hasn't run yet. */
export function getDb(): DB {
  if (!_db) throw new Error('Database not initialized — call initDb() first.');
  return _db;
}
